#!/bin/bash

# general

alias nr="npm run"
alias bci='brew install --cask'
alias bci='brew install --cask'
alias bcr='brew reinstall --cask'
alias bcu='brew uninstall --cask'
alias bi='brew install'
alias bs='brew search'
alias bu='brew uninstall'
alias defd='defaults delete'
alias defre='defaults read'
alias deft='defaults read-type'
alias ls='ls -G -F -A'
alias r='source ~/.zshrc'
alias j=z
alias vim=nvim
alias lg=lazygit
alias cat=bat
alias ls="eza -la --icons"

alias amend="gca -n --no-edit --amend"
alias ga="git add"
alias gc="git commit"
alias gca="git add . && git commit -a"
alias gcam="gca -m"
alias gcf="git add . && git fixup"
alias gdf="git diff"
alias gl="git log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gpl="git pull"
alias gpr="git pull --rebase"
alias gpu="git push"
alias gr="git restore"
alias gs="git status"
alias gsh="git show"
alias gsl="git stash list"
alias gsp="git stash pop"
alias gst="git stash"
alias gtl="git tag -l"

alias update="brew update; brew upgrade; mas upgrade"

alias cc="claude --dangerously-skip-permissions"
alias cx="codex --dangerously-bypass-approvals-and-sandbox"
alias ca="cursor-agent -f"

function gcampu() {
	gca -m "$1" && git push
}
